version: '3'
services:
  wallabag:
    image: abhilesh7/wallabag-arm
    container_name: wallabag_app
    environment:
      - MYSQL_ROOT_PASSWORD=<secure-root-password>                           # Change this
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=<password>                           # Change this
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=smtp.gmail.com                             # Using gmail's smtp server
      - SYMFONY__ENV__MAILER_USER=<smtp-user>                                # Change this
      - SYMFONY__ENV__MAILER_PASSWORD=<smtp-user-password>                   # Change this
      - SYMFONY__ENV__FROM_EMAIL=<smtp-user-email>                           # Change this
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.example.com               # Change this
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
    # If using watchtower, uncomment the line below to disable automatic updates
    #labels:
    #  - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8543:80                                                              # Serving on port '8543', can change to a different port
    volumes:
      - /opt/wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
  db:
    image: mariadb
    container_name: wallabag_db
    environment:
      - MYSQL_ROOT_PASSWORD=<secure-root-password>
    volumes:
      - /opt/wallabag/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
  redis:
    image: redis:alpine
    container_name: wallabag_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

