---
version: "2.1"
services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC                                   # Change this
      - RATE_LIMIT=false                             # optional
      - WS_FALLBACK=false                            # optional
      - RTC_CONFIG=                                  # optional
      - DEBUG_MODE=false                             # optional
    ports:
      - 8080:3000                                    # Change this <external-ip:internal-ip>
    restart: unless-stopped
