---
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000                                             # Change to PUID=0 for running Duplicati as root
      - PGID=1000                                             # Change to PUID=0 for running Duplicati as root
      - TZ=America/Chicago                                    # Change this
      - CLI_ARGS= #optional                                   # Additional CLI_args can be specified from  https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/
    volumes:
      - /home/pi/duplicati/config:/config 
      - /mnt/nfs-share/Duplicati_backups:/backups             # Duplicati Backups are stored here
      - /mnt/nfs-source:/source:ro                            # Directories to backup (Remove ro while restoring backups)
    ports:
      - 8200:8200
    restart: unless-stopped