---
version: "2.1"
services:
  homeassistant:
    image: linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host                         # Required for device discovery
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/pi/home-assistant:/config        # Config directory
      - /mnt/nfs-share:/extstorage             # External storage mounted directly for some integrations
   #ports:
   #   - 8123:8123 #optional
   #devices:
   #   - /path/to/device:/path/to/device
    restart: unless-stopped
